### ISSUE TITLE
 [winerror 2] the system cannot find the specified file

### ISSUE THREAD

**Issue by gueat** [ysdede/swf2png#1]
When I get to ffmpeg.input (file name = "title = Adobe e flash player 34") the system always prompts [winerror 2] that the specified file cannot be found

**Comment by ysdede** [comment]
Hi. Can you check your flash player executable's title? It must match with ffmpeg input parameter.
It's "Adobe Flash Player 32" for flashplayer_32_sa.exe.
You can download same version from [https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa.exe](https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flashplayer_32_sa.exe) then copy it under "/util" directory.

Thank you for feedback. I edited Readme for better explanation.

**Comment by gueat** [comment]
Thank you for your answer. The flash player I used is version 34. The ffmpeg parameter has been changed to the same as the title, but this problem still occurs. I think it's the problem of ffmpeg. When I test ffmpeg alone, the same error will be reported

**Comment by gueat** [comment]
Traceback (most recent call last):
  File "E:/demo/online_spider/onedb_api/swf_to_png/swf2png-master/main.py", line 87, in <module>
    renderpng(output_folder + outputfilename)
  File "E:/demo/online_spider/onedb_api/swf_to_png/swf2png-master/main.py", line 69, in renderpng
    .run(quiet=True, overwrite_output=True)
  File "E:\tool\swf_image\lib\site-packages\ffmpeg\_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

The previous problem was that I didn't download ffmpeg's exe program. After I downloaded it, I could do it. Then I reported an error during the conversion. I don't know what this means

**Comment by ysdede** [comment]
Hi. Sorry my bad. There is lots of ffmpeg python wrappers installed on my system globally. I confused about which ffmpeg wrapper projects uses. So requirements.txt was incorrect. I edited requirements.txt and readme.
I hope this works.

**Comment by gueat** [comment]
Hi, thank you for your help. All the problems have been solved and the program can run normally
